# Generated by Django 4.2 on 2023-05-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='titleModels',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='contentModels',
            field=models.TextField(blank=True, null=True),
        ),
    ]
