# Generated by Django 4.2 on 2023-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_slugmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slugModels',
            field=models.SlugField(default='hhh'),
        ),
    ]
