# Generated by Django 4.2 on 2023-05-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_slugmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BlogPostModels',
        ),
    ]
