# Generated by Django 4.2 on 2023-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_blogpost_blogpostmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodels',
            name='titleModels',
            field=models.CharField(max_length=100),
        ),
    ]
