# Generated by Django 4.2 on 2023-07-10 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpostmodels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodels',
            name='publushed_dateME',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostmodels',
            name='timestampMe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostmodels',
            name='updatedMe',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
